version: '3.4'

networks:
  dev:
    driver: bridge

services:
  webapi:
    container_name: MotorcyclesAPI
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile    
    ports:
      - ${WEBAPI_PORT}:${WEBAPI_PORT}
    depends_on:
      - postgresql
    networks:
      - dev

  frontend:
    container_name: MotorcyclesUI
    image: motorcyclesfrontend:latest
    build: ../MotorcyclesFrontend
    ports:
      - "4200:4200"
    depends_on:
      - postgresql
    networks:
      - dev

  postgresql:
    container_name: PostgreSQL
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5442:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  db-data: