// <auto-generated />
using System;
using Infrastructure.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MotorcycleDataContext))]
    [Migration("20230319000049_Add Subscriptions Entity")]
    partial class AddSubscriptionsEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApplicationCore.Models.Entities.Motorcycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EnginePower")
                        .HasColumnType("integer");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Motorcycles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9de0146-4a48-4d18-80d9-99d95ec451ff"),
                            Company = "Triumph",
                            EnginePower = 70,
                            ModelName = "Bonnevile T100",
                            ModelType = "Naked",
                            Price = 14000.0
                        },
                        new
                        {
                            Id = new Guid("6fb6397b-6dd9-499d-ac10-15f616663cfa"),
                            Company = "Kawasaki",
                            EnginePower = 7,
                            ModelName = "KLX110R",
                            ModelType = "Motocross",
                            Price = 3195.0
                        },
                        new
                        {
                            Id = new Guid("aa29ae7e-0515-48c5-82db-aa1a1422798b"),
                            Company = "BMW",
                            EnginePower = 136,
                            ModelName = "R 1250 RS",
                            ModelType = "Sport",
                            Price = 20000.0
                        });
                });

            modelBuilder.Entity("ApplicationCore.Models.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
